### ISSUE TITLE
What I want to do after Capture the login password which is encrypted?

### ISSUE THREAD

**Issue by 2kpurple** [yon2kong/Poseidon#1]
Hi, what I want to do after Capture the login password which is encrypted?
Go to the step 2 directly?

Can you help me~.3q~

**Comment by yonzkon** [comment]
@2kpurple 
I have added another STEP 2 about how to use the login password.
Try it and good luck.

**Comment by 2kpurple** [comment]
@yon2kong Thank you very much!!!

**Comment by 2kpurple** [comment]
@yon2kong I can log in Account Server now, but can not connect the char server.

I can not get this output like your pic.

![](https://github.com/yon2kong/Poseidon/blob/master/doc/poseidon3.png)
