### ISSUE TITLE
character_info size error

### ISSUE THREAD

**Issue by hubertyang88** [yon2kong/Poseidon#12]
client is updated today , there is a character_info size error , character_info size 147 
what should I do ?poseidon work with old client,but "Unknown switch"

**Comment by hubertyang88** [comment]
封包也更新了，直接用ok登录，看到很多未知封包

**Comment by happyero** [comment]
![image](https://user-images.githubusercontent.com/34304934/33976382-6f7d8e04-e0cf-11e7-9526-2a5b45b380fa.png)
无法找到怪物
