### ISSUE TITLE
12月14日，更新完，poseidon出问题了。求帮助

### ISSUE THREAD

**Issue by skices** [yon2kong/Poseidon#13]
CHARACTER_INFO size error!!
CHARACTER_INFO size 147

开poseidon客户端进不了角色画面

**Comment by hubertyang88** [comment]
用旧版exe文件，poseidon还是可以用，但是封包不对了，有兴趣一起研究下吗

**Comment by skices** [comment]
一个一个去解封包，不会解，查了几个封包解析器还有以前几个老的，全部无法解析
