### ISSUE TITLE
大佬问个问题啊，openkore是和poseidon在VM里启动，还是和客户端一起在主机上启动？

### ISSUE THREAD

**Issue by skices** [yon2kong/Poseidon#3]
英文不是太好，看您的教程，没完全看明白，弄了两天中国服务器，还是没把poseidon正常的搞起来。求大佬帮助，另外XML这样设置是否有问题？

<?xml version="1.0" encoding="euc-kr" ?>

<clientinfo>

	<desc>Ragnarok Client Information - China Test</desc>
	<servicetype>china</servicetype>
	<servertype>primary</servertype>
	<hideaccountlist></hideaccountlist>
	
	<connection>
		<display>Poseidon</display>
		<desc>None</desc>
                <address>127.0.0.1</address>
		<port>6900</port>
		<domain>acc.ro.zhaouc.com:6900</domain>
		<version>1</version>
		<langtype>3</langtype>
		<registrationweb>http://ro.zhaouc.com/</registrationweb>
		<aid>
			<admin>100006</admin>
			<admin>100007</admin>
			<admin>129255</admin>
			<admin>129257</admin>
		</aid>
	</connection>

</clientinfo>
tinfo>

**Comment by yonzkon** [comment]
@skices XML配置错了。

![poseidon xml](https://user-images.githubusercontent.com/7730121/32130504-2dd7e13e-bbcc-11e7-8cff-3198ac6c3a99.png)

**Comment by skices** [comment]
@yon2kong poseidon是在vm里启动，那openkore主程序是在哪里启动？ro的客户端又在哪里启动呢？
您写的STEP 1，wpe无法注入，有np保护。如何解决呢？
STEP5，英文都能看懂，但是全部加起来就看不懂是什么意思了......CHECK OUT，如何CHECK OUT？
YOUR VM IP可以填127.0.0.1吗？
大佬能不能用中文稍微解释一下，程序小白跪谢了
