### ISSUE TITLE
如何在windows系统下运行您的poseidon。

### ISSUE THREAD

**Issue by skices** [yon2kong/Poseidon#4]
或者大佬能否写一个windows下的步骤。。。

**Comment by yonzkon** [comment]
1) - Download & Install "Strawberry Perl".   http://strawberryperl.com/
2) - Run cmd.exe and cd \<THE POSEIDON DIRECTORY\>
3) - input "perl src/poseidon.pl --char-server=\<YOUR VM IP:6900\> --map-server=\<YOUR VM IP:6900\>"

**Comment by skices** [comment]
搞定了poseidon，现在要去学STEP1怎么弄了。。
