### ISSUE TITLE
大佬我又来了，为什么我的openkore没有通过poseidon，poseidon正常运行

### ISSUE THREAD

**Issue by skices** [yon2kong/Poseidon#5]
=========================== Server Infos ===========================
EXP Rates: 200% (Base 100% + Premium 0% + Server 100% + Plus 0%) 
Drop Rates: 100% (Base 100% + Premium 0% + Server 0% + Plus 0%) 
Death Penalty: 100% (Base 100% + Premium 0% + Server 0% + Plus 0%) 
=====================================================================
You are no longer: UNKNOWN_STATUS_993
You are no longer: UNKNOWN_STATUS_994
Calculating random route to: 印特羅 (iz_int): 106, 100
Your Ragnarok Online server uses GameGuard. In order to support GameGuard, you must use the Poseidon server. Please read http://wiki.openkore.com/index.php?title=Poseidon for more information.
断开连接 (118.89.31.79:10004)...中断
Openkore will stay disconnected. Type "connect" in order to connect again.

openkore还要设置什么地方？

**Comment by skices** [comment]
怎么样设置openkore能让openkore连接poseidon，我的openkore现在是直接连接cro，和poseidon无关

**Comment by skices** [comment]
@yon2kong 我正常进行到第四步，第五步看不懂，而且openkore不知道怎么设置能和poseidon服务器关联起来，您能不能用易懂的方式解释一下第五步，还有怎么把openkore和poseidon关联起来

**Comment by yonzkon** [comment]
@skices 配置好config.txt就可以把openkore和poseidon关联起来的。
原来的STEP1放在STEP4前更合适。
我调整了下使用步骤。

**Comment by skices** [comment]
@yon2kong 

Calculating random route to: 印特羅 (iz_int): 97, 99
[S] 曦小曦㊣ : WE加油！！！！！
Calculating random route to: 印特羅 (iz_int): 119, 93
Calculating random route to: 印特羅 (iz_int): 100, 95
Calculating random route to: 印特羅 (iz_int): 110, 91
Calculating random route to: 印特羅 (iz_int): 86, 92
Calculating random route to: 印特羅 (iz_int): 92, 96
[S] 卡洛斯。㊣ : 金字塔工资队来1老板1游侠 107+ 来个肝到双倍结束的
Calculating random route to: 印特羅 (iz_int): 99, 84
The Poseidon server closed the connection unexpectedly or could not respond to your request due to a server bandwidth issue. Please report this bug.
断开连接 (118.89.31.79:10004)...中断
Openkore will stay disconnected. Type "connect" in order to connect again.

连上去一会就这样了，大佬知道是怎么回事吗？poseidon显示如下：

Poseidon Query(09150200): cf0914002bb7c072ad0f506badfda0b3246d6ed7
no free ragnarok-client left!

客户端侦测到非法程序。。。

**Comment by yonzkon** [comment]
@skices 
Poseidon的配置确实比较复杂，有些东西我说不知道怎么才能说清楚。。。
我重写了README，希望能帮到你。
Good luck.

**Comment by skices** [comment]
@yon2kong 我已经成功挂上了。。太感谢您了，这么热心的给我一个小白慢慢讲解。
