### ISSUE TITLE
用了您的openkore for cro,团队技能模块（partyskill）不正常，大佬能看看吗？

### ISSUE THREAD

**Issue by skices** [yon2kong/Poseidon#7]
牧师设置了partyskill之后，一直对自己不断的释放技能，直到SP用完。完全无视队伍中其他人的状态。

大佬您能看看是不是程序语句出了问题吗？谢谢了

**Comment by yonzkon** [comment]
@skices 
我拉了最新的openkore master代码，这个问题已经解决了。
你更新下cro分支就能正常。
还有我写得Poseidon不支持内挂模式。

**Comment by happyero** [comment]
已经更新最新的CRO，但是运行10秒就退出
