### ISSUE TITLE
运行Poseidon时报错

### ISSUE THREAD

**Issue by hubertyang88** [yon2kong/Poseidon#8]
Can't locate object method "autoflush" via package "IO::File" at src/poseidon.pl line 18.
这个是什么问题？是我的perl安装有问题吗？还是Poseidon应该放在指定的目录下？

**Comment by yonzkon** [comment]
重装perl，或装个别的版本的

**Comment by hubertyang88** [comment]
回复真快啊
换了新版perl ， Poseidon initialized.  但是客户端连接不上

使用的命令：perl src/poseidon.pl --char-server=127.0.0.1:6900 --map-server=127.0.0.1:6900

客户端参数 ：E:\RO\仙境传说online\Ragexe.exe 1rag1 /account:poseidon.xml

poseidon.xml:
<?xml version="1.0" encoding="euc-kr" ?>

<clientinfo>

	<desc>Ragnarok Client Information - China Test</desc>
	<servicetype>china</servicetype>
	<servertype>primary</servertype>
	<hideaccountlist></hideaccountlist>
	
	<connection>
		<display>普隆德拉</display>
		<desc>None</desc>
		<port>6900</port>
		<domain>127.0.0.1</domain>
		<version>1</version>
		<langtype>3</langtype>
		<registrationweb>http://ro.zhaouc.com/</registrationweb>
		<aid>
			<admin>100006</admin>
			<admin>100007</admin>
		</aid>
	</connection>

</clientinfo>
tinfo>

**Comment by yonzkon** [comment]
@hubertyang88 
\<domain\>这一行不对
改成：\<domain\>127.0.0.1:6900\</domain\>

**Comment by hubertyang88** [comment]
poseidon终于好了，非常感谢！！

**Comment by yonzkon** [comment]
不用Poseidon，挂不了10秒就会断线的

**Comment by hubertyang88** [comment]
VM软件也会被nP检查出来，有什么好建议吗？在局域网中用另外一台电脑运行openkore？
