### ISSUE TITLE
Poseidon servercould not respond to your request due to a server bandwidth issue.

### ISSUE THREAD

**Issue by Jelle-Wu** [yon2kong/Poseidon#9]
Poseidon server OS:centOS 7.4.1708
perl version:5.16.3

only one openkore session in running.

i've set the posedion server but  it could not relay my query as below.

_Poseidon initialized.
accept client(5) 192.168.1.62:6623
Poseidon Query(d53c0200): cf0948000c472991278e522236d578b3481ca14434f9575467b792842fd85c831ffebd43d06ec5a30b4d807430f460b73a7ca1df0c99254659f49047becb46f849adffcc67eefbfe
no free ragnarok-client left!
close client(5) 192.168.1.62:6623_

config file:
_poseidonServer 192.168.1.70
poseidonPort 24390_

**Comment by yonzkon** [comment]
@vasa1983 You should run cro-client slaves before running OpenKore.
Go back to  STEP 1.3

**Comment by Jelle-Wu** [comment]
I run posedion on VM(192.168.1.70) and run RO-client & openkore on local.But RO-cilent will start GameGuade ,GameGuade will detect openkore and kill itself.

_Poseidon initialized.
accept client(5) 192.168.1.62:7647
close client(5) 192.168.1.62:7647
accept client(5) 192.168.1.62:7648
close client(5) 192.168.1.62:7648
accept client(5) 192.168.1.62:7653
accept client(6) 192.168.1.62:7654
Poseidon Query(d53c0200): cf0948000c472991278e522236d578b3481ca1440a4cd18ed3506f004e33cb8d00a1a157fc711f3e83b90ea15b82b2c851e9c8f7dd80f69ef282c2ca6941c2f10846f2ad6f4b5724
Poseidon Reply(d53c0200): cf0948000c472991278e522236d578b3481ca1440a4cd18ed3506f004e33cb8d00a1a157fc711f3e83b90ea15b82b2c851e9c8f7dd80f69ef282c2ca6941c2f10846f2ad6f4b5724 => d00950000c472991208e502236d578b3481ca144386da6cce67291a4f28f51ecbda102ccf1fd6b6fb7b2a97fcef0139a34adffdfaf9bbbfed7baa90521e650a32539816200b9f8437f567270cfcfaf5c
close client(6) 192.168.1.62:7654
accept client(6) 192.168.1.62:7656
Poseidon Query(d53c0200): cf0948000c472991268e502236d578b3481ca1444e33cb8d00a1a157fc711f3e83b90ea167b6e9e3d75d21e749191cdb06ca9cfd22e9e4a0630702f49b7403c3f8ba644d172383be
Poseidon Reply(d53c0200): cf0948000c472991268e502236d578b3481ca1444e33cb8d00a1a157fc711f3e83b90ea167b6e9e3d75d21e749191cdb06ca9cfd22e9e4a0630702f49b7403c3f8ba644d172383be => d00960007234332adc686454449d967eb0d1c8a8cb156a2d25f22ecaeb18822966573d0d07341562442d5b4dcef0139a34adffdf388b1e8c98cff5d463fb247d9393b66a9e4dd4229fbbc19a06dd6665f41f125ee7ea587e1ad25c4b5798033d
close client(6) 192.168.1.62:7656
close client(5) 192.168.1.62:7653
no free ragnarok-client left!
accept client(5) 192.168.1.62:7679
Poseidon Query(d53c0200): cf0948000c472991268e502236d578b3481ca1444e33cb8d00a1a157fc711f3e83b90ea18d5f169467a9761e4ade1311a6e6f3780080b1d9b59a5615fc8b87fb0ca08d0367e6e73e
no free ragnarok-client left!
close client(5) 192.168.1.62:7679_

how could i fix the problem?run openkore on another client?
If run openkore on another client is the way,how could I run multi-openkore?Can one RO-client handle all openkore?

**Comment by yonzkon** [comment]
@vasa1983 
One cro-client can only handle one OpenKore.

Run OpenKore inside VM...
